/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grewords;

import com.mongodb.BasicDBObject;
import java.net.UnknownHostException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Bishwajit
 */
class Fields {
    String viewed, word, meaning, category, example;
    Long lastSeen;
}

public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    DbManager dbManager = null;
    private String name = "gre"; // Database name and collection name are the same.

    public Welcome() {
        super("Welcome");
        initComponents();
        initDatabase();
        System.out.println("Everything is OK!!!");
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    void initDatabase() {
        try {
            dbManager = new DbManager(name);
        } catch (UnknownHostException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        viewedLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastSeenLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        wordTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        secondaryPanel = new javax.swing.JPanel();
        moreLabel = new javax.swing.JLabel();
        startsWithLabel = new javax.swing.JLabel();
        startsWithTextField = new javax.swing.JTextField();
        startsWithLabel1 = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        goButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addWordMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 235, 66));

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Word");

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Detail");

        detailTextArea.setEditable(false);
        detailTextArea.setColumns(20);
        detailTextArea.setRows(5);
        jScrollPane1.setViewportView(detailTextArea);

        jLabel3.setBackground(new java.awt.Color(204, 0, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Viewed");

        viewedLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewedLabel.setText("100 Times");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Last Seen");

        lastSeenLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastSeenLabel.setText("Today");

        jButton3.setText("jButton3");
        jButton3.setPreferredSize(new java.awt.Dimension(73, 2));

        changeButton.setText("Change");
        changeButton.setMaximumSize(new java.awt.Dimension(73, 23));
        changeButton.setMinimumSize(new java.awt.Dimension(73, 23));
        changeButton.setPreferredSize(new java.awt.Dimension(73, 23));
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.setMaximumSize(new java.awt.Dimension(73, 23));
        nextButton.setMinimumSize(new java.awt.Dimension(73, 23));
        nextButton.setPreferredSize(new java.awt.Dimension(73, 23));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        wordTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wordTextField.setText("wonder");
        wordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordTextFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(viewedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastSeenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(wordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 81, Short.MAX_VALUE)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewedLabel)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastSeenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        secondaryPanel.setBackground(new java.awt.Color(255, 235, 66));

        moreLabel.setBackground(new java.awt.Color(204, 0, 204));
        moreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        moreLabel.setForeground(new java.awt.Color(0, 102, 102));
        moreLabel.setText("More!!!");

        startsWithLabel.setBackground(new java.awt.Color(204, 0, 204));
        startsWithLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startsWithLabel.setForeground(new java.awt.Color(0, 102, 102));
        startsWithLabel.setText("Starts With...");

        startsWithLabel1.setBackground(new java.awt.Color(204, 0, 204));
        startsWithLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startsWithLabel1.setForeground(new java.awt.Color(0, 102, 102));
        startsWithLabel1.setText("Viewed");

        yesRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yesRadioButton.setText("Yes");

        noRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noRadioButton.setText("No");

        goButton.setText("Go!");

        javax.swing.GroupLayout secondaryPanelLayout = new javax.swing.GroupLayout(secondaryPanel);
        secondaryPanel.setLayout(secondaryPanelLayout);
        secondaryPanelLayout.setHorizontalGroup(
            secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondaryPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startsWithLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startsWithLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondaryPanelLayout.createSequentialGroup()
                        .addGroup(secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(secondaryPanelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(moreLabel))
                            .addGroup(secondaryPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startsWithTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(secondaryPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yesRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(noRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        secondaryPanelLayout.setVerticalGroup(
            secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondaryPanelLayout.createSequentialGroup()
                .addComponent(moreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startsWithTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startsWithLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startsWithLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yesRadioButton)
                        .addComponent(noRadioButton))
                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jMenu1.setText("File");

        addWordMenuItem.setText("Add New Word");
        addWordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addWordMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(secondaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(secondaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addWordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordMenuItemActionPerformed
        // TODO add your handling code here:
        new ChangeWord(this, null, "Add New Word");
    }//GEN-LAST:event_addWordMenuItemActionPerformed

    public Fields findWord(String word) {
        String[] res = dbManager.searchWord(word), temp;
        if (res == null) {
            String message = "The word is not in the dictionary. "
                    + "Do you want to add it?";
            String title = "Cofirmation";
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                new ChangeWord(this, null, "Add New Word");
            } else {
                JOptionPane.showMessageDialog(null, "GOODBYE");
            }
            return null;
        }
        Fields fields = new Fields();
        String meaning, type, viewed;
        fields.lastSeen = System.currentTimeMillis();
        /*
         res[0]: {_id=58ba66e90645e51f3a9dedce
         res[1]:  word=wonder
         res[2]:  meaning=nice
         res[3]:  type=verb
         res[4]:  viewed=0.0
         res[5]:  lastseen=1.4883264E12}
         */
        temp = res[1].split("=");
        fields.word = temp[1];
        temp = res[2].split("=");
        fields.meaning = temp[1];
        temp = res[3].split("=");
        fields.category = temp[1];
        temp = res[4].split("=");
        fields.example = temp[1];
        temp = res[5].split("=");
        temp = temp[1].split("[.]");
        fields.viewed = temp[0];
        Long systemMillis = System.currentTimeMillis();
        temp = res[6].split("=");
        temp[1] = temp[1].substring(0, temp[1].length() - 1);
        Double then = 0.0;
        try {
            then = Double.parseDouble(temp[1]);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        Double diff = systemMillis - then;
        int days = (int) (diff / 1000.0 / 86400.0);
        String detail = fields.word + " means " + fields.meaning + ".\nCategory: "
                + fields.category + ".\nExample: " + fields.example;

        detailTextArea.setText(detail);
        viewedLabel.setText(fields.viewed + " times");
        if (days < 1) {
            lastSeenLabel.setText("Today");
        } else {
            lastSeenLabel.setText(String.valueOf(days) + " days ago.");
        }
        return fields;
    }
    
    private void update(Fields fields){
        // Now update viewed and Lastseen
        ArrayList<String> strings = new ArrayList<>();
        Integer v = Integer.parseInt(fields.viewed) + 1;
        strings.add("word");
        strings.add(fields.word);
        strings.add("viewed");
        strings.add(v.toString());
        strings.add("lastseen");
        strings.add(fields.lastSeen.toString());
        dbManager.changeItem(strings);
        
    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String word = wordTextField.getText();
        word = word.toLowerCase();
        Fields fields = findWord(word);
        if (fields == null) {
            return;
        }
        update(fields);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void wordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordTextFieldActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
        String word = wordTextField.getText();
        word = word.toLowerCase();
        if (word.equals("")) {
            JOptionPane.showMessageDialog(null, "No word given for change!!!");
            return;
        }
        Fields fields = findWord(word);
        if (fields == null) {
            return;
        }
        new ChangeWord(this, fields, "Change a Word");
    }//GEN-LAST:event_changeButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        String word = wordTextField.getText();
        if(word.equals("")){
            JOptionPane.showMessageDialog(this, "No words given to remove!!!");
            return ;
        }
        dbManager.removeItem(word);
        JOptionPane.showMessageDialog(this, "Successfully done!!!");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        String[] res = dbManager.randomWord(), temp;
        if (res == null) {
            String message = "There is no word in the dictionary. "
                    + "Do you want to add?";
            String title = "Cofirmation";
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                new ChangeWord(this, null, "Add New Word");
            } else {
                JOptionPane.showMessageDialog(null, "GOODBYE");
            }
            return;
        }
        Fields fields = new Fields();
        String meaning, type, viewed;
        fields.lastSeen = System.currentTimeMillis();
        /*
         res[0]: {_id=58ba66e90645e51f3a9dedce
         res[1]:  word=wonder
         res[2]:  meaning=nice
         res[3]:  type=verb
         res[4]:  viewed=0.0
         res[5]:  lastseen=1.4883264E12}
         */
        temp = res[1].split("=");
        fields.word = temp[1];
        temp = res[2].split("=");
        fields.meaning = temp[1];
        temp = res[3].split("=");
        fields.category = temp[1];
        temp = res[4].split("=");
        fields.example = temp[1];
        temp = res[5].split("=");
        temp = temp[1].split("[.]");
        fields.viewed = temp[0];
        Long systemMillis = System.currentTimeMillis();
        temp = res[6].split("=");
        temp[1] = temp[1].substring(0, temp[1].length() - 1);
        Double then = 0.0;
        try {
            then = Double.parseDouble(temp[1]);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        Double diff = systemMillis - then;
        int days = (int) (diff / 1000.0 / 86400.0);
        String detail = fields.word + " means " + fields.meaning + ".\nCategory: "
                + fields.category + ".\nExample: " + fields.example;

        wordTextField.setText(fields.word);
        detailTextArea.setText(detail);
        viewedLabel.setText(fields.viewed + " times");
        if (days < 1) {
            lastSeenLabel.setText("Today");
        } else {
            lastSeenLabel.setText(String.valueOf(days) + " days ago.");
        }
        update(fields);
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addWordMenuItem;
    private javax.swing.JButton changeButton;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JButton goButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastSeenLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel moreLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel secondaryPanel;
    private javax.swing.JLabel startsWithLabel;
    private javax.swing.JLabel startsWithLabel1;
    private javax.swing.JTextField startsWithTextField;
    private javax.swing.JLabel viewedLabel;
    private javax.swing.JTextField wordTextField;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
